name: Python CI/CD

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    env:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TRAVILY_API_KEY}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Project Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Development Dependencies
        run: |
          pip install pytest
          pip install pytest-cov
          pip install black
          pip install isort
          pip install flake8

      - name: Check Code Formatting (Black)
        run: |
          black --check .

      - name: Check Import Order (isort)
        run: |
          isort --check-only .

      - name: Lint Code (Flake8)
        run: |
          flake8 . --count --statistics

      - name: Run Unit Tests
        run: |
          pytest tests -v --cov=. --cov-report=term-missing

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: .coverage
